name: Keep Render Instance Alive

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

jobs:
  keep_alive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to keep the server alive
        run: curl -X GET https://qeja-backend.onrender.com
